--TRIGGER(트리거)

CREATE TABLE TR(
	TRNO NUMBER PRIMARY KEY,
	TRCONT VARCHAR2(200)
);

--시퀀스
CREATE SEQUENCE SEQ_TR;

--로그테이블
CREATE TABLE TR_LOG(
	LOGNO NUMBER PRIMARY KEY,
	TNAME VARCHAR2(20),	--테이블명
	DML VARCHAR2(20),	--컬럼명
	OLDCONT VARCHAR2(200),	--기존데이터
	NEWCONT VARCHAR2(200),	--신규데이터
	LOGDATE DATE	--로그일시
);

--시퀀스
CREATE SEQUENCE SEQ_TR_LOG;

--트리거
CREATE OR REPLACE TRIGGER TRG_TR
BEFORE
INSERT OR UPDATE OR DELETE ON TR
FOR EACH ROW
BEGIN 
	IF INSERTING THEN 
		INSERT INTO TR_LOG
		VALUES(SEQ_TR_LOG.NEXVAL,'TR','INSERT', :OLD.TRCONT, :NEW.TRCONT, SYSDATE);
	ELSIF UPDATING THEN 
		INSERT INTO TR_LOG
		VALUES(SEQ_TR_LOG.NEXVAL,'TR','UPDATE', :OLD.TRCONT, :NEW.TRCONT, SYSDATE);
	ELSIF DELETING THEN 
		INSERT INTO TR_LOG
		VALUES(SEQ_TR_LOG.NEXVAL,'TR','DELETE', :OLD.TRCONT, :NEW.TRCONT, SYSDATE);
	END IF;
END;

DROP TRIGGER TRG_TR;

SELECT * FROM TR;

INSERT INTO TR VALUES(SEQ_TR.NEXTVAL,'1번 컨텐츠');

