-- procedure (프로시져)

-- 익명프로시져, 저장(네임드)프로시져

DROP PROCEDURE PROC_PRINT_PERSON;

CREATE OR REPLACE PROCEDURE PROC_PRINT_PERSON
IS
	V_PNAME PERSON.PNAME%TYPE;
	V_PAGE PERSON.PAGE%TYPE;
BEGIN 
	SELECT PNAME, PAGE INTO V_PNAME, V_PAGE FROM PERSON;
	DBMS_OUTPUT.PUT_LINE(V_PNAME ||' '|| V_PAGE);
END;

COMMIT;

BEGIN
		PROC_PRINT_PERSON;
END;

