CREATE TABLE CAR (
	CID NUMBER PRIMARY KEY,
	CCOMPANY VARCHAR2(200) NOT NULL,
	CNAME VARCHAR2(200) NOT NULL,
	CDISPALTMENT NUMBER,
	CCOLOR VARCHAR2(200),
	CPRICE NUMBER
);

DROP TABLE CAR ;
TRUNCATE TABLE car;



CREATE SEQUENCE SEQ_CAR;

DROP SEQUENCE seq_car;

SELECT value$ FROM sys.props$ WHERE name = 'NLS_CHARACTERSET'