CREATE TABLE CONN_LOG (
	CLNO NUMBER PRIMARY KEY,
	CLIP VARCHAR2(200),
	CLURI VARCHAR2(200),
	CLTS TIMESTAMP
);

CREATE SEQUENCE SEQ_CL;

SELECT * FROM CONN_LOG cl ;

TRUNCATE TABLE CONN_LOG ;

