CREATE  TABLE PERSON(
	PID NUMBER PRIMARY KEY,
	NAME VARCHAR2(200),
	AGE NUMBER
)
DROP TABLE PERSON;
TRUNCATE TABLE PERSON;



CREATE SEQUENCE SEQ_PERSON;
DROP  SEQUENCE SEQ_PERSON;
SELECT * FROM Person;