CREATE TABLE BLOG(
	BLOG_ID NUMBER PRIMARY KEY,
	BLOG_NAME VARCHAR2(200),
	BLOG_TITLE VARCHAR2(1000),
	BLOG_AUTHOR_ID NUMBER
);
TRUNCATE TABLE BLOG ;
DROP TABLE BLOG ;

CREATE SEQUENCE SEQ_BLOG;
DROP SEQUENCE SEQ_BLOG;

SELECT * FROM BLOG;

CREATE TABLE COMM (
	COMM_ID NUMBER PRIMARY KEY,
	COMM_TITLE VARCHAR2(200),
	COMM_CONTENT VARCHAR2(4000),
	BLOG_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(BLOG_ID)
);
DROP TABLE COMM ;
CREATE SEQUENCE SEQ_COMM;
DROP SEQUENCE SEQ_COMM;
TRUNCATE TABLE COMM ;
SELECT * FROM COMM ;


CREATE TABLE AUTHOR (
	AUTHOR_ID NUMBER PRIMARY KEY,
	AUTHOR_NAME VARCHAR2(200),
	BLOG_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(BLOG_ID)
);
DROP TABLE author ;
TRUNCATE TABLE AUTHOR ;
CREATE SEQUENCE SEQ_AUTHOR;

SELECT * FROM AUTHOR;


	select b.blog_id, b.blog_name, b.blog_title, b.blog_author_id
			,a.author_id, a.author_name, a.blog_id
			,c.comm_id,c.comm_title, c.comm_content, c.blog_id
	from blog b
		left outer join author a on b.blog_id = a.blog_id
		left outer join comm c on b.blog_id = c.blog_id