-- java프로젝트
-- java,JDBC, Oracle데이터베이스를 활용한 프로젝트 만들기
-- 주제 : 맛집리스트 만들기
-- 가게이름  음식카테고리 주소 주요메뉴 메뉴가격 별점(5점 만점 기준 ) 한줄후기
-- 카테고리별로 리스트 조회기능
-- 가능하면  gui만들어서 데이터 넣어보기

CREATE TABLE TASTY_RESTAURANT_LIST(
   TID NUMBER PRIMARY KEY, 
	RESTAURANT_NAME VARCHAR2(50) NOT NULL ENABLE,
	FOOD_CATEGORY VARCHAR2(20), 
	RESTAURANT_IP VARCHAR2(100), 
	RESTAURANT_MENU VARCHAR2(100), 
	MENU_PRICE NUMBER,
	RESTAURANT_SCORE NUMBER CHECK (RESTAURANT_SCORE BETWEEN 0 AND 5),
	RESTAURANT_REVIEW VARCHAR2(50), 
	TREGDATE TIMESTAMP
	);
	
DROP TABLE TASTY_RESTAURANT_LIST;

COMMIT;
CREATE SEQUENCE SEQ_TASTY_RESTAURANT_LIST;
DROP SEQUENCE SEQ_TASTY_RESTAURANT_LIST;

SELECT * FROM TASTY_RESTAURANT_LIST trl ;

CREATE OR REPLACE PROCEDURE PROC_INSERT_TASTY
( 
	P_RESTAURANT_NAME IN TASTY_RESTAURANT_LIST.RESTAURANT_NAME%TYPE,
	P_FOOD_CATEGORY IN TASTY_RESTAURANT_LIST.FOOD_CATEGORY%TYPE,
	P_RESTAURANT_IP IN TASTY_RESTAURANT_LIST.RESTAURANT_IP%TYPE,
	P_RESTAURANT_MENU IN TASTY_RESTAURANT_LIST.RESTAURANT_MENU%TYPE,
	P_MENU_PRICE IN TASTY_RESTAURANT_LIST.MENU_PRICE%TYPE,
	P_RESTAURANT_SCORE IN TASTY_RESTAURANT_LIST.RESTAURANT_SCORE%TYPE,
	P_RESTAURANT_REVIEW IN TASTY_RESTAURANT_LIST.RESTAURANT_REVIEW%TYPE
	)
IS BEGIN 
	INSERT INTO TASTY_RESTAURANT_LIST 
	VALUES(SEQ_TASTY_RESTAURANT_LIST.NEXTVAL, P_RESTAURANT_NAME,
	P_FOOD_CATEGORY, P_RESTAURANT_IP,P_RESTAURANT_MENU,  
	P_MENU_PRICE, P_RESTAURANT_SCORE, P_RESTAURANT_REVIEW, SYSDATE);
END;



BEGIN 
	PROC_INSERT_TASTY('식당', '중식', 'ㄴ' , 'ㅇㅇㄹ', '12000', '3', 'ㄴㅇㄴㅇㅇ' );
END;
