-- java프로젝트
-- java,JDBC, Oracle데이터베이스를 활용한 프로젝트 만들기
-- 주제 : 맛집리스트 만들기
-- 가게이름  음식카테고리 주소 주요메뉴 메뉴가격 별점(5점 만점 기준 ) 한줄후기
-- 카테고리별로 리스트 조회기능
-- 가능하면  gui만들어서 데이터 넣어보기

CREATE TABLE TASTY_RESTAURANT_LIST(
   TID NUMBER PRIMARY KEY, 
	RESTAURANT_NAME VARCHAR2(50) NOT NULL ENABLE,
	FOOD_CATEGORY VARCHAR2(20), 
	RESTAURANT_IP VARCHAR2(200), 
	RESTAURANT_MENU VARCHAR2(100), 
	MENU_PRICE NUMBER,
	RESTAURANT_SCORE NUMBER CHECK (RESTAURANT_SCORE BETWEEN 0 AND 5),
	RESTAURANT_REVIEW VARCHAR2(200), 
	TREGDATE TIMESTAMP
	);
	

CREATE TABLE SD(
TID AS "번호" IS NUMBER PRIMARY KEY, 
	RESTAURANT_NAME AS "식당이름" IS VARCHAR2(50) NOT NULL ENABLE
);


DROP TABLE TASTY_RESTAURANT_LIST;
TRUNCATE TABLE TASTY_RESTAURANT_LIST;

COMMIT;
CREATE SEQUENCE SEQ_TASTY_RESTAURANT_LIST;

INSERT INTO TASTY_RESTAURANT_LIST
VALUES(SEQ_TASTY_RESTAURANT_LIST.NEXTVAL, 
				'가야불닭발', '야식', '서울 관악구 신원로 26 1층 ', '국물닭발 ',18000,4.5,'사장님이 친절하고 닭발이랑 콘치즈 굿',SYSDATE);
				
SELECT * FROM TASTY_RESTAURANT_LIST trl ;


UPDATE TASTY_RESTAURANT_LIST SET RESTAURANT_NAME=? ,FOOD_CATEGORY=? , RESTAURANT_IP=?, RESTAURANT_MENU=?, MENU_PRICE=?, RESTAURANT_SCORE=?, RESTAURANT_REVIEW=?, TID =?;
--한 행의 데이터를 입력하는 프로시져
CREATE OR REPLACE PROCEDURE PROC_INSERT_TASTY
( 
P_RESTAURANT_NAME IN TASTY_RESTAURANT_LIST.RESTAURANT_NAME%TYPE,
P_FOOD_CATEGORY IN TASTY_RESTAURANT_LIST.FOOD_CATEGORY%TYPE,
P_RESTAURANT_IP IN TASTY_RESTAURANT_LIST.RESTAURANT_IP%TYPE,
P_RESTAURANT_MENU IN TASTY_RESTAURANT_LIST.RESTAURANT_MENU%TYPE,
P_MENU_PRICE IN TASTY_RESTAURANT_LIST.MENU_PRICE%TYPE,
P_RESTAURANT_SCORE IN TASTY_RESTAURANT_LIST.RESTAURANT_SCORE%TYPE,
P_RESTAURANT_REVIEW IN TASTY_RESTAURANT_LIST.RESTAURANT_REVIEW%TYPE
	)
IS BEGIN 
	INSERT INTO TASTY_RESTAURANT_LIST
	VALUES(SEQ_TASTY_RESTAURANT_LIST.NEXTVAL, P_RESTAURANT_NAME, P_FOOD_CATEGORY, 
					P_RESTAURANT_IP, P_RESTAURANT_MENU, P_MENU_PRICE, 
					P_RESTAURANT_SCORE, P_RESTAURANT_REVIEW, SYSDATE);
END;

--한 행의 데이터를 입력한 후에 전체행의 수를 out파라미터로 전달하는 프로시져
CREATE OR REPLACE PROCEDURE PROC_INSERT2
	(P_BTITLE IN BOARD.BTITLE%TYPE,
	P_BCONTENT IN BOARD.BCONTENT%TYPE,
	CNT	OUT NUMBER)
IS BEGIN 
	INSERT INTO BOARD 
	VALUES(SEQ_BOARD.NEXTVAL, P_BTITLE, P_BCONTENT, SYSDATE);
SELECT COUNT(*) INTO CNT FROM BOARD;
END;


SELECT TID, RESTAURANT_NAME, FOOD_CATEGORY, RESTAURANT_IP, RESTAURANT_MENU, MENU_PRICE, RESTAURANT_SCORE, RESTAURANT_REVIEW, TREGDATE 
FROM TASTY_RESTAURANT_LIST;

BEGIN 
	PROC_INSERT_TASTY('가야불닭발', '야식', '서울 관악구 신원로 26 1층 ', '국물닭발 ',18000,4.5,'사장님이 친절하고 닭발이랑 콘치즈 굿');
END;

UPDATE TASTY_RESTAURANT_LIST SET RESTAURANT_SCORE = 2.5 WHERE tid = 13;
